apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-front-deployment
spec:
  selector:
   matchLabels:
    app: angular-front
  replicas: 2
  template:
    metadata:
      labels:
        app: angular-front
    spec:
      containers:
        - name: flutter
          image: flutter:prueba 
          ports:
            - containerPort: 80
              name: angularfport